# 07_plssem_bridge.R
# PLS-SEM model specification via seminr, matching TF v2.4 Table 1 / SS C.1 / SS C.3.
# Called from Python via rpy2 (see run_plssem.py). Not run standalone for reporting -
# always cross-validate against SmartPLS 4 output before a number goes in the manuscript
# (CLAUDE.md SS5).
#
# FIXED 2026-08-26 (see NOTE at bottom for the full change list):
#  - `lib` (line 11 of the previous version) was not valid R and would error on
#    source() -- fixed to library(seminr).
#  - H7 interaction terms rebuilt for Amendment A-8: TWO independent two-way terms
#    (INT*PDPL -> TRU, beta_M1, H7a; INT*DISC -> TRU, beta_M2, H7b) via the two-stage
#    approach (Becker et al., 2018). The three-way term (beta_M4) is retired and does
#    NOT appear anywhere below.
# UPDATED 2026-09-10, reconciled against Master Codebook v2.5 / TF v2.9 and the
# actual PROJ_MAIN raw export (pilot_real.csv):
#  - AIP is AIP1-5 (was 1-6; the self-reference item was dropped for AIP-REL
#    content-validity reasons).
#  - REL is REL1-4, ALL analysed. Amendment A-9's REL4 exclusion no longer
#    applies -- that applied only to the old (Tam & Ho, 2006) REL4 item, since
#    removed from the instrument. The current REL4 (Yin, Qiu & Wang, 2025) is a
#    different, unrelated item and is fully included.
#  - PI is PI1-4 (was 1-3; PI4 added from Dodds, Monroe & Grewal, 1991).
#  - TRU is TRU1-6 (was reduced to 5 by Amendment A-10, then reverted back to 6
#    by a post-B1.5 correction pass explicitly superseding A-10 for TRU -- see
#    TF v2.11 amendment log and the note in src/_config.py). This is the
#    ratified, current state, not an open item.
#  - The `ave = model$rSquared` placeholder was wrong on two counts: rSquared is R^2,
#    not AVE, and it isn't even the reliability table. Replaced with the real
#    summary(model)$reliability extraction, which also gives rhoA (Dijkstra-Henseler),
#    closing the "Cronbach's alpha and rhoA > 0.70" requirement in TF v2.4 SS C.3 that
#    the Python pilot script (03_reliability_efa.py) can only approximate.
#
# DISC_COND enters as an OBSERVED DUMMY predictor. seminr requires every construct
# used in an interaction_term() or in paths() to be declared via constructs(), so
# DISC_COND is wrapped as a single-item composite named "DISC" below -- this is a
# measurement-model formality for seminr, NOT a reversal of the rule that DISC is
# never a Likert/reflective construct. DISC has one indicator (DISC_COND itself),
# no loadings table is meaningful for it, and none should be reported for it.
#
# SMOKE-TESTED 2026-08-26 against data/processed/main_clean.csv (synthetic, n=336
# after complete-case filtering) with seminr 2.5.0 / R 4.6.1. estimate_pls(),
# bootstrap_model(), interaction_term(..., method=two_stage), and single_item() all
# ran and returned the expected shapes. One real bug was caught and fixed: seminr
# does not export a standalone HTMT() function (only plot_htmt/dot_graph_htmt) -- the
# HTMT matrix is under summary(model)$validity$htmt, which is what this script now
# uses. summary(model)$reliability column names (alpha/rhoA/rhoC/AVE) matched the
# assumption already in this file -- no change needed there.
#
# STILL TO DO before real main-collection data: the rpy2 Python<->R round-trip in
# run_plssem.py has NOT been executed on this machine -- rpy2 3.6.7 fails at import
# because `R CMD config --ldflags` returns empty without Rtools/make on PATH (a
# Windows-without-Rtools limitation, not an rpy2 or script bug). Installing Rtools
# would resolve it; until then, treat run_plssem.py itself as still unverified even
# though the R-side logic it calls (this file) is now confirmed working directly via
# Rscript.

library(seminr)

run_plssem <- function(data) {

  # ---- Measurement model ----
  # Reflective constructs use their fielded, analysed item sets (Amendments A-9, A-10).
  # DISC is a single-item composite wrapping the observed dummy -- see note above.
  # The two interaction_term() calls are H7a and H7b (Amendment A-8): TWO independent
  # two-way terms, generated by the two-stage approach per TF v2.4 SS C.2. There is
  # no three-way interaction_term() call anywhere in this model.
  measurements <- constructs(
    composite("AIP",  multi_items("AIP", 1:5)),    # 5 items (self-reference item dropped)
    composite("REL",  multi_items("REL", 1:4)),    # 4 items, all analysed (REL4 no longer excluded)
    composite("INT",  multi_items("INT", 1:5)),
    composite("TRU",  multi_items("TRU", 1:6)),    # 6 items (ratified, see _config.py TRU note)
    composite("ENG",  multi_items("ENG", 1:6)),
    composite("PI",   multi_items("PI", 1:4)),     # 4 items (PI4 added)
    composite("PDPL", multi_items("PDPL", 1:4)),
    composite("DISC", single_item("DISC_COND")),
    interaction_term(iv = "INT", moderator = "PDPL", method = two_stage),  # H7a, beta_M1
    interaction_term(iv = "INT", moderator = "DISC", method = two_stage)  # H7b, beta_M2
  )

  # ---- Structural model ----
  # Hypotheses: H1 AIP->REL, H2 AIP->INT, H4 REL->TRU, H5 REL->ENG,
  #             H6a INT->TRU, H6b INT->ENG, H6c INT->PI,
  #             H7a INT*PDPL->TRU (beta_M1), H7b INT*DISC->TRU (beta_M2)
  # Established paths (not hypotheses): E1 TRU->ENG, E2 ENG->PI
  # Specification terms (not hypotheses, required because an interaction is
  # uninterpretable without its lower-order components -- Aiken & West, 1991):
  #   DISC->INT (this is NOT a second test of H3 -- H3's sole confirmatory test is
  #              the two-way ANOVA main effect in 05_anova_h3.py; TF v2.4 SS C.1.1)
  #   PDPL->TRU  (lower-order term for the H7a interaction)
  #   DISC->TRU  (lower-order term for the H7b interaction)
  structure <- relationships(
    paths(from = "AIP",  to = c("REL", "INT")),
    paths(from = "REL",  to = c("TRU", "ENG")),
    paths(from = "INT",  to = c("TRU", "ENG", "PI")),
    paths(from = "TRU",  to = "ENG"),          # E1
    paths(from = "ENG",  to = "PI"),           # E2
    paths(from = "DISC", to = "INT"),          # specification term, NOT a second H3 test
    paths(from = "PDPL", to = "TRU"),          # specification term for H7a
    paths(from = "DISC", to = "TRU"),          # specification term for H7b
    paths(from = "INT*PDPL", to = "TRU"),      # H7a: beta_M1
    paths(from = "INT*DISC", to = "TRU")       # H7b: beta_M2
  )

  model <- estimate_pls(data = data, measurement_model = measurements,
                         structural_model = structure, missing_value = NA)

  boot <- bootstrap_model(seminr_model = model, nboot = 10000, cores = NULL, seed = 123)

  # summary(model)$reliability carries alpha, rhoC (composite reliability), AVE, and
  # rhoA (Dijkstra-Henseler) together -- this is the real statistic TF v2.4 SS C.3
  # requires ("Cronbach's alpha and rhoA > 0.70"), which 03_reliability_efa.py's
  # Python CR/AVE table can only approximate at pilot stage. VERIFY the exact column
  # name for rhoA in your installed seminr version (see file header note).
  reliability_tab <- summary(model)$reliability

  # Inner VIF (2026-09-17, requested by Khai) -- the standard PLS-SEM
  # collinearity/CMB diagnostic (Kock, 2015 "full collinearity" convention:
  # inner VIF > 3.3 is a red flag for common method bias; > 5 is the more
  # lenient generic-multicollinearity threshold). summary(model)$vif_antecedents
  # is NOT a rectangular matrix -- it's a named list, one entry per ENDOGENOUS
  # (dependent) construct, each a named numeric vector of VIF values for that
  # construct's own predictors (verified directly against a live model: 5
  # entries -- REL, INT, TRU, ENG, PI -- each holding only its own
  # antecedents' VIFs, e.g. TRU's entry has 6 values for
  # REL/INT/PDPL/DISC/INT*PDPL/INT*DISC). Flatten to a tidy (to, from, vif)
  # data.frame here so it survives the rpy2/pandas round-trip in
  # run_plssem.py cleanly, instead of shipping the nested list across.
  vif_list <- summary(model)$vif_antecedents
  vif_rows <- do.call(rbind, lapply(names(vif_list), function(to_construct) {
    v <- vif_list[[to_construct]]
    data.frame(to = to_construct, from = names(v), vif = as.numeric(v),
               stringsAsFactors = FALSE)
  }))

  # Fornell-Larcker criterion (2026-09-19, requested by Khai): sqrt(AVE) on the
  # diagonal, inter-construct correlations on the lower triangle -- discriminant
  # validity holds when each diagonal exceeds every correlation in its row/column.
  # Restricted to the 7 reflective constructs: DISC and the two interaction terms
  # are single-item composites (AVE = 1 by construction), so FL says nothing
  # about them (same reason DISC never gets HTMT/alpha reporting, CLAUDE.md SS0).
  # Outer VIF (item-level collinearity WITHIN a construct; distinct from the inner
  # VIF above, which is construct-level and used for CMB). Flattened to tidy
  # (construct, item, vif); single-item constructs skipped for the same reason.
  # PDPL before PI = seminr's own construct order, so the lower triangle stays lower.
  reflective <- c("AIP", "REL", "INT", "TRU", "ENG", "PDPL", "PI")
  fl_full <- summary(model)$validity$fl_criteria
  fl_tab <- fl_full[reflective, reflective]
  vif_items_list <- summary(model)$validity$vif_items
  outer_vif_rows <- do.call(rbind, lapply(reflective, function(cn) {
    v <- vif_items_list[[cn]]
    data.frame(construct = cn, item = names(v), vif = as.numeric(v),
               stringsAsFactors = FALSE)
  }))

  # f2 gap fix (2026-09-19): seminr's model_fsquares() deliberately sets f2 = NA
  # for every COMPONENT of an interaction term (here INT, PDPL, DISC -> TRU),
  # with its own comment that omitting them "will cause model estimation to
  # fail". That is not a formula error (no R2_reduced > R2_full or divide-by-0):
  # it is a blanket skip. Checked directly: dropping INT->TRU or DISC->TRU DOES
  # estimate (each still has other structural paths), so seminr's own per-path
  # fSquared() is called on them here. PDPL->TRU genuinely cannot be
  # estimated without the path ("subscript out of bounds": PDPL would then
  # appear only inside the interaction term), so it stays NA.
  f2_tab <- summary(model)$fSquare
  for (iv in c("INT", "PDPL", "DISC")) {
    f2_tab[iv, "TRU"] <- tryCatch(seminr:::fSquared(model, iv, "TRU"),
                                  error = function(e) NA_real_)
  }

  # Specific indirect effects (2026-09-19, requested by Khai; extended 2026-09-23
  # for the manuscript's Table 10 -- "and other indirect paths"): product of the
  # path coefficients along from->through->to, evaluated on EVERY one of the same
  # 10,000 bootstrap resamples used for the path table (same boot object, same
  # seed), so the CI is the percentile CI of the product -- not a Sobel/normal
  # approximation. `through` can be a vector (seminr::specific_effect_significance
  # supports serial mediation chains up to 4 mediators) -- used here for the two
  # 3-step chains through TRU then ENG.
  ind_specs <- list(
    list(from = "REL", through = "TRU", to = "ENG"),          # H4 x E1
    list(from = "INT", through = "TRU", to = "ENG"),          # H6a x E1
    list(from = "REL", through = "ENG", to = "PI"),           # H5 x E2
    list(from = "INT", through = "ENG", to = "PI"),           # H6b x E2
    list(from = "REL", through = c("TRU", "ENG"), to = "PI"), # H4 x E1 x E2 (serial)
    list(from = "INT", through = c("TRU", "ENG"), to = "PI")  # H6a x E1 x E2 (serial)
  )
  indirect_rows <- do.call(rbind, lapply(ind_specs, function(sp) {
    r <- specific_effect_significance(boot, from = sp$from, through = sp$through, to = sp$to)
    data.frame(effect = paste(c(sp$from, sp$through, sp$to), collapse = "->"),
               estimate = as.numeric(r[1, "Original Est."]),
               boot_mean = as.numeric(r[1, "Bootstrap Mean"]),
               boot_sd = as.numeric(r[1, "Bootstrap SD"]),
               ci_low = as.numeric(r[1, "2.5% CI"]),
               ci_high = as.numeric(r[1, "97.5% CI"]),
               p_boot = as.numeric(r[1, "Bootstrap P Val"]),
               stringsAsFactors = FALSE)
  }))

  # R^2 / Adjusted R^2 per endogenous construct (2026-09-23, requested by Khai,
  # for the manuscript's "R^2 and Q2predict" table). model$rSquared is a 2-row
  # matrix (Rsq, AdjRsq) x endogenous constructs -- transposed here into a tidy
  # (construct, R2, AdjR2) data.frame.
  rsq_m <- model$rSquared
  rsquared_tab <- data.frame(construct = colnames(rsq_m),
                              R2 = as.numeric(rsq_m["Rsq", ]),
                              AdjR2 = as.numeric(rsq_m["AdjRsq", ]),
                              stringsAsFactors = FALSE)

  # Q2predict (Shmueli, Ray, Estrada & Danks, 2019 PLSpredict routine): 10-fold,
  # 10-repetition out-of-sample prediction via seminr::predict_pls(). Q2predict
  # per indicator = 1 - SSE/SSO, SSE from the held-out prediction error returned
  # by predict_pls(), SSO from each indicator's deviation around the FULL-SAMPLE
  # mean (the standard reporting approximation -- predict_pls() does not expose
  # per-fold training-set means, which the strict blindfolding definition uses).
  # Reported per ENDOGENOUS construct (REL, INT, TRU, ENG, PI) as the mean across
  # that construct's own indicators, alongside the PLS-vs-LM-benchmark RMSE
  # comparison Shmueli et al. (2019) use to grade predictive power (High = PLS
  # beats the naive linear-model benchmark on every indicator; Medium = majority;
  # Low/none = minority or none).
  set.seed(123)
  pred <- predict_pls(model, noFolds = 10, reps = 10, cores = NULL)
  pred_sum <- summary(pred)
  pe <- pred_sum$prediction_error
  pls_rmse <- pred_sum$PLS_out_of_sample["RMSE", ]
  lm_rmse <- pred_sum$LM_out_of_sample["RMSE", ]
  endogenous_items <- list(
    REL = multi_items("REL", 1:4), INT = multi_items("INT", 1:5),
    TRU = multi_items("TRU", 1:6), ENG = multi_items("ENG", 1:6),
    PI = multi_items("PI", 1:4)
  )
  q2predict_tab <- do.call(rbind, lapply(names(endogenous_items), function(cons) {
    items <- endogenous_items[[cons]]
    q2_item <- sapply(items, function(it) {
      e <- pe[[it]]
      sso <- sum((data[[it]] - mean(data[[it]]))^2)
      1 - sum(e^2) / sso
    })
    n_pls_better <- sum(pls_rmse[items] < lm_rmse[items])
    # Q2predict <= 0 means NO predictive relevance regardless of the RMSE-vs-LM
    # comparison (Shmueli et al. 2019) -- checked here first so a construct like
    # INT (tiny/negative R2, so its indicators are barely predictable by anything)
    # cannot be mislabeled "High" purely because PLS's poor predictions still beat
    # an equally poor LM benchmark on RMSE.
    power <- if (mean(q2_item) <= 0) "None (Q2predict <= 0)" else
      if (n_pls_better == length(items)) "High" else
      if (n_pls_better > length(items) / 2) "Medium" else "Low"
    data.frame(construct = cons, Q2predict = mean(q2_item),
               n_items_PLS_lt_LM_RMSE = n_pls_better, n_items_total = length(items),
               predictive_power = power, stringsAsFactors = FALSE)
  }))

  list(
    indirect = indirect_rows,
    rsquared = rsquared_tab,
    q2predict = q2predict_tab,
    boot_obj = boot,                      # kept for ad hoc reuse of the fitted bootstrap object; no in-repo consumer as of the 2026-09-23 cleanup (was 09_h7_supplementary.py, removed)
    model_obj = model,
    fornell_larcker = fl_tab,
    outer_vif = outer_vif_rows,
    loadings = model$outer_loadings,
    weights = model$outer_weights,
    reliability = reliability_tab,        # alpha, rhoC, AVE, rhoA per construct
    path_coefficients = model$path_coef,
    f_squared = f2_tab,                   # individual f2 per path, incl. beta_M1/beta_M2
    htmt = summary(model)$validity$htmt,  # HTMT() is not exported by seminr; the
                                           # matrix lives under summary(model)$validity
    vif = vif_rows,                       # inner VIF, tidy (to, from, vif) -- see note above
    boot_paths = summary(boot)$bootstrapped_paths
  )
}

# NOTE: Change list vs. the version this replaces (which was byte-identical to the
# pipeline's initial upload and had never actually been edited):
#  1. DONE -- H7a (INT*PDPL) and H7b (INT*DISC) interaction terms added via
#     interaction_term(..., method = two_stage), per TF v2.4 SS C.2 (Amendment A-8).
#     The old NOTE calling for "beta_M1-beta_M4" and a "full product term" described
#     the RETIRED three-way specification -- not carried forward.
#  2. PLS-MGA / MICOM is NO LONGER REQUIRED for H7 (Amendment A-8): DISC is now a
#     pooled predictor/moderator inside one model, not a between-group factor for a
#     three-way contrast. If PLS-MGA is used elsewhere (e.g. a demographic robustness
#     check), MICOM remains a prerequisite for THAT use -- it is simply no longer part
#     of the H7 estimation strategy.
#  3. DONE -- the `ave = model$rSquared` placeholder (wrong statistic entirely) is
#     replaced by a real reliability() extraction carrying alpha/rhoC/AVE/rhoA.
#  4. STILL REQUIRED, unchanged: cross-validate every reported number against
#     SmartPLS 4 before manuscript use (CLAUDE.md SS5), and verify the seminr call
#     signatures against your local install per the file-header note above -- this
#     script was authored without a local R/seminr session available to execute
#     against.
