# 07_plssem_bridge.R
# PLS-SEM model specification via seminr, matching TF v2.4 Table 1 / SS C.1 / SS C.3.
# Called from Python via rpy2 (see run_plssem.py). Not run standalone for reporting -
# always cross-validate against SmartPLS 4 output before a number goes in the manuscript
# (CLAUDE.md SS5).
#
# FIXED 2026-08-26 (see NOTE at bottom for the full change list):
#  - `lib` (line 11 of the previous version) was not valid R and would error on
#    source() -- fixed to library(seminr).
#  - H7 interaction terms rebuilt for Amendment A-8: TWO independent two-way terms
#    (INT*PDPL -> TRU, beta_M1, H7a; INT*DISC -> TRU, beta_M2, H7b) via the two-stage
#    approach (Becker et al., 2018). The three-way term (beta_M4) is retired and does
#    NOT appear anywhere below.
#  - TRU/ENG item counts (TRU1-5, ENG1-6) are the ratified counts (Amendment A-10) --
#    the previous GOVERNANCE-OPEN comments on this are removed; it is resolved.
#  - REL is REL1-3 only (Amendment A-9, REL4 excluded from the measurement model).
#  - The `ave = model$rSquared` placeholder was wrong on two counts: rSquared is R^2,
#    not AVE, and it isn't even the reliability table. Replaced with the real
#    summary(model)$reliability extraction, which also gives rhoA (Dijkstra-Henseler),
#    closing the "Cronbach's alpha and rhoA > 0.70" requirement in TF v2.4 SS C.3 that
#    the Python pilot script (03_reliability_efa.py) can only approximate.
#
# DISC_COND enters as an OBSERVED DUMMY predictor. seminr requires every construct
# used in an interaction_term() or in paths() to be declared via constructs(), so
# DISC_COND is wrapped as a single-item composite named "DISC" below -- this is a
# measurement-model formality for seminr, NOT a reversal of the rule that DISC is
# never a Likert/reflective construct. DISC has one indicator (DISC_COND itself),
# no loadings table is meaningful for it, and none should be reported for it.
#
# VERIFY BEFORE RUNNING ON REAL DATA: interaction_term(), single_item(), and the
# exact column names inside summary(model)$reliability can differ slightly across
# seminr versions. Run `?interaction_term`, `?single_item`, and inspect
# `colnames(summary(model)$reliability)` in your local R session before trusting the
# output structure this script assumes -- this was written without a local R/seminr
# install available to execute against, so treat the seminr call signatures below as
# a best-effort draft, not a verified-by-execution one.

library(seminr)

run_plssem <- function(data) {

  # ---- Measurement model ----
  # Reflective constructs use their fielded, analysed item sets (Amendments A-9, A-10).
  # DISC is a single-item composite wrapping the observed dummy -- see note above.
  # The two interaction_term() calls are H7a and H7b (Amendment A-8): TWO independent
  # two-way terms, generated by the two-stage approach per TF v2.4 SS C.2. There is
  # no three-way interaction_term() call anywhere in this model.
  measurements <- constructs(
    composite("AIP",  multi_items("AIP", 1:6)),
    composite("REL",  multi_items("REL", 1:3)),    # REL4 excluded (A-9)
    composite("INT",  multi_items("INT", 1:5)),
    composite("TRU",  multi_items("TRU", 1:5)),    # ratified (A-10)
    composite("ENG",  multi_items("ENG", 1:6)),    # ratified (A-10)
    composite("PI",   multi_items("PI", 1:3)),
    composite("PDPL", multi_items("PDPL", 1:4)),
    composite("DISC", single_item("DISC_COND")),
    interaction_term(iv = "INT", moderator = "PDPL", method = two_stage),  # H7a, beta_M1
    interaction_term(iv = "INT", moderator = "DISC", method = two_stage)  # H7b, beta_M2
  )

  # ---- Structural model ----
  # Hypotheses: H1 AIP->REL, H2 AIP->INT, H4 REL->TRU, H5 REL->ENG,
  #             H6a INT->TRU, H6b INT->ENG, H6c INT->PI,
  #             H7a INT*PDPL->TRU (beta_M1), H7b INT*DISC->TRU (beta_M2)
  # Established paths (not hypotheses): E1 TRU->ENG, E2 ENG->PI
  # Specification terms (not hypotheses, required because an interaction is
  # uninterpretable without its lower-order components -- Aiken & West, 1991):
  #   DISC->INT (this is NOT a second test of H3 -- H3's sole confirmatory test is
  #              the two-way ANOVA main effect in 05_anova_h3.py; TF v2.4 SS C.1.1)
  #   PDPL->TRU  (lower-order term for the H7a interaction)
  #   DISC->TRU  (lower-order term for the H7b interaction)
  structure <- relationships(
    paths(from = "AIP",  to = c("REL", "INT")),
    paths(from = "REL",  to = c("TRU", "ENG")),
    paths(from = "INT",  to = c("TRU", "ENG", "PI")),
    paths(from = "TRU",  to = "ENG"),          # E1
    paths(from = "ENG",  to = "PI"),           # E2
    paths(from = "DISC", to = "INT"),          # specification term, NOT a second H3 test
    paths(from = "PDPL", to = "TRU"),          # specification term for H7a
    paths(from = "DISC", to = "TRU"),          # specification term for H7b
    paths(from = "INT*PDPL", to = "TRU"),      # H7a: beta_M1
    paths(from = "INT*DISC", to = "TRU")       # H7b: beta_M2
  )

  model <- estimate_pls(data = data, measurement_model = measurements,
                         structural_model = structure, missing_value = NA)

  boot <- bootstrap_model(seminr_model = model, nboot = 10000, cores = NULL, seed = 123)

  # summary(model)$reliability carries alpha, rhoC (composite reliability), AVE, and
  # rhoA (Dijkstra-Henseler) together -- this is the real statistic TF v2.4 SS C.3
  # requires ("Cronbach's alpha and rhoA > 0.70"), which 03_reliability_efa.py's
  # Python CR/AVE table can only approximate at pilot stage. VERIFY the exact column
  # name for rhoA in your installed seminr version (see file header note).
  reliability_tab <- summary(model)$reliability

  list(
    loadings = model$outer_loadings,
    weights = model$outer_weights,
    reliability = reliability_tab,        # alpha, rhoC, AVE, rhoA per construct
    path_coefficients = model$path_coef,
    f_squared = summary(model)$fSquare,   # individual f2 per path, incl. beta_M1/beta_M2
    htmt = HTMT(model),
    boot_paths = summary(boot)$bootstrapped_paths
  )
}

# NOTE: Change list vs. the version this replaces (which was byte-identical to the
# pipeline's initial upload and had never actually been edited):
#  1. DONE -- H7a (INT*PDPL) and H7b (INT*DISC) interaction terms added via
#     interaction_term(..., method = two_stage), per TF v2.4 SS C.2 (Amendment A-8).
#     The old NOTE calling for "beta_M1-beta_M4" and a "full product term" described
#     the RETIRED three-way specification -- not carried forward.
#  2. PLS-MGA / MICOM is NO LONGER REQUIRED for H7 (Amendment A-8): DISC is now a
#     pooled predictor/moderator inside one model, not a between-group factor for a
#     three-way contrast. If PLS-MGA is used elsewhere (e.g. a demographic robustness
#     check), MICOM remains a prerequisite for THAT use -- it is simply no longer part
#     of the H7 estimation strategy.
#  3. DONE -- the `ave = model$rSquared` placeholder (wrong statistic entirely) is
#     replaced by a real reliability() extraction carrying alpha/rhoC/AVE/rhoA.
#  4. STILL REQUIRED, unchanged: cross-validate every reported number against
#     SmartPLS 4 before manuscript use (CLAUDE.md SS5), and verify the seminr call
#     signatures against your local install per the file-header note above -- this
#     script was authored without a local R/seminr session available to execute
#     against.
